### ISSUE TITLE
Footer con espacio en blanco en vista celular

### ISSUE THREAD

**Issue by jforni** [Valentin1Quiroga/Rolling-Cucina#69]
Si bien entiendo que hay una tabla, queda un espacio en blanco en el footer que se podría cubrir.
![Footer con blancos](https://user-images.githubusercontent.com/6042663/226722652-da695017-1df2-4544-9e1c-097574705b74.jpg)

**Comment by Valentin1Quiroga** [comment]
Corregido. Se solucionó el faltante de la clase Responsive de "Bootstrap" a la tabla.

![image](https://user-images.githubusercontent.com/107730331/226746374-92c707eb-46ec-4a1e-9e97-bb46f8dbcf28.png)
