### ISSUE TITLE
Tengan cuidado cuando crean usuarios de prueba.

### ISSUE THREAD

**Issue by jforni** [Valentin1Quiroga/Rolling-Cucina#70]
Cuando crean usuarios de prueba, tengan cuidado con lo que eligen y que no queden para cuando un tercero realiza testeos. 
![Nombres de usuarios en pruebas](https://user-images.githubusercontent.com/6042663/226723012-5e8e519a-5ff5-4508-b786-84b543d7af89.jpg)

**Comment by Valentin1Quiroga** [comment]
Solucionado. Se editó el nombre y el correo 
![issue1](https://user-images.githubusercontent.com/107730331/226745959-539dd9f9-8257-4a83-ac17-f0e66723a5dc.png)
